version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    image: isae_back_end:latest
    container_name: isae_backend_container
    ports:
      - 8000:8000

  frontend:
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    image: isae_front_end:latest
    container_name: isae_frontend_container
    ports:
      - 8501:8501
    volumes:
      - ./src/front_end:/streamlit_app
